### PR TITLE
feat: add 2 conventions

### PR DESCRIPTION
**Pull request by Rignchen**
- add load convention:
> The load folder allow the user of the datapack library to have a better control over the order in which the different libraries get loaded

- add global convention:
> The global advancements are advancements a non obstrusive way to give visibility to the developer
> They are given on player login and don't show in chat or the top of the screen meaning they won't be annoying to the player, however when the player opens it's advancements page they can see an "Installed Datapacks" window where they can see a list of all datapack installed respecting this convention linked to their author
> I put your github username there as I didn't know your minecraft username

### CODE REVIEW

**Comment by SilicatYT** [comment]
Thanks for the pull request.

Is the load convention used by a lot of packs, or just something that a specific developer or group of developers use? If it's a known standard, I'd be happy to add it to StringLib. But if it's something very niche, I'm not sure

Edit: I asked in the MCC discord, and I was told that the global advancement convention is old, with its community being inactive. But I'll happily merge the load convention, thank you for bringing that up. However, the files you committed still use the pre-1.21 paths, so I'll quickly add it manually and close this pull request.

Is this okay with you?

**Comment by Rignchen** [comment]
hi yea of course totally fine with me, I last time I did datapacks was in 1.20.4 (I think, maybe .5) so it's not surprising that I did something that's not up to date (+I don't have mc on this computer so I cannot ensure it works)

I know multiple datapack dev (almost all the ones I talk to on discord) were using the global convention last time I did mcfunction and convention or not I still belive it's a nice way to credit the dev

the load convention was initialy a library but it got so used by every other library that it became a convention, I've seen it a lot in datapacks requiering libraries

**Comment by Rignchen** [comment]
I'm currently making a split function for your stringlib, I have written the algorithm and manually transpiled it in python to test it, it works in python but I currently wasn't able to test it in minecraft

here's the doc I wrote in the function
```
##########################################################################################################
##                                              HOW TO USE                                              ##
##########################################################################################################
## 1. Set the following data in the 'stringlib:input split' data storage:                               ##
##    - String: Original string                                                                         ##
##    - Separator: String you want to replace                                                           ##
##    - n: How many times should the string get splited                                                 ##
##        - Unset or 0: All                                                                             ##
##        - Positive: First n                                                                           ##
##        - Negative: Last -n                                                                           ##
## 2. Run this function                                                                                 ##
##                                                                                                      ##
## Output: String with all the 'Find' instances replaced by 'Replace'                                   ##
##         Example:                                                                                     ##
##                 - String: "Hello World !"                                                            ##
##                 - Separator: " "                                                                     ##
##                 - Amount: 1                                                                          ##
##                 => Output: ["Hello", "World !"]                                                      ##
##                                                                                                      ##
##                 - String: "Hello World !"                                                            ##
##                 - Separator: " "                                                                     ##
##                 - Amount: 0                                                                          ##
##                 => Output: ["Hello", "World", "!"]                                                   ##
##                                                                                                      ##
##                 - String: "2 + 2 + 4 = 8"                                                            ##
##                 - Separator: "+"                                                                     ##
##                 - Amount: -1                                                                         ##
##                 => Output: ["2 + 2 ", " 4 = 8"]                                                      ##
##                                                                                                      ##
## Return value: Number of texts in the output storage                                                  ##
##                                                                                                      ##
## The output is found in the 'stringlib:output split' data storage                                     ##
##########################################################################################################
```

**Comment by SilicatYT** [comment]
I'm also currently working on a split function. Am I understanding correctly that you haven't started converting it to Minecraft commands yet?
Thanks to the find and replace algorithms, I already have a pretty good idea of how to efficiently implement it. I did not, however, think of allowing 'n' to be set for this function. That's a good idea.

**Comment by Rignchen** [comment]
No, I actually started by doing it in mcfunction, then because I wasn't able to test it I transpiled it in python, fixed the problems in my algo, report the modifications in my mcfunction and I'm currently doing shit with git to make the history be a bit nicer.

The whole thing is done but altho I tested my algorithm in another language I didn't test it in mc

If I were you I wouldn't spend more time on the split function

**Pull request closed without merging**
